// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RMS_Backend.Data;

#nullable disable

namespace RMS_Backend.Migrations
{
    [DbContext(typeof(RMSDbContext))]
    [Migration("20231224184354_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RMS_Backend.Models.PublicationScopus", b =>
                {
                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<string>("Authors")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorsNo")
                        .HasColumnType("integer");

                    b.Property<int?>("Pages")
                        .HasColumnType("integer");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DOI");

                    b.HasIndex("PersonnelNumber");

                    b.ToTable("PublicationsScopus");
                });

            modelBuilder.Entity("RMS_Backend.Models.PublicationWebOfScience", b =>
                {
                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<string>("Authors")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorsNo")
                        .HasColumnType("integer");

                    b.Property<int?>("Pages")
                        .HasColumnType("integer");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DOI");

                    b.HasIndex("PersonnelNumber");

                    b.ToTable("PublicationsWebOfScience");
                });

            modelBuilder.Entity("RMS_Backend.Models.User", b =>
                {
                    b.Property<string>("PersonnelNumber")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Faculty")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonnelNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RMS_Backend.Models.PublicationScopus", b =>
                {
                    b.HasOne("RMS_Backend.Models.User", "User")
                        .WithMany("PublicationsScopus")
                        .HasForeignKey("PersonnelNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RMS_Backend.Models.PublicationWebOfScience", b =>
                {
                    b.HasOne("RMS_Backend.Models.User", "User")
                        .WithMany("PublicationsWebOfScience")
                        .HasForeignKey("PersonnelNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RMS_Backend.Models.User", b =>
                {
                    b.Navigation("PublicationsScopus");

                    b.Navigation("PublicationsWebOfScience");
                });
#pragma warning restore 612, 618
        }
    }
}
